Repository golemfactory/concent, pull requests merged in 2018-04, with the labels that each got.

#248 Add subtask_id to FileTransferToken from nested TaskToCompute
  concent_api/core/tests/test_auth_get_task_result.py
  concent_api/core/tests/test_integration_get_task_result.py
  concent_api/core/transfer_operations.py
Labels: bug, result transfer use case

#260 Change gatekeeper content_type to 'multipart/form-data'
  concent_api/gatekeeper/tests/test_gatekeeper_views.py
  concent_api/gatekeeper/views.py
Labels: urgent

#269 Fix annotation
  concent_api/core/validation.py
Labels: urgent

#273 Fix for verification of task_to_compute signature is wrong
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_auth_accept_or_reject_results.py
  concent_api/core/tests/test_auth_get_task_result.py
  concent_api/core/tests/test_auth_report_computed_task.py
  concent_api/core/tests/utils.py
  concent_api/utils/tests/test_api_view.py
Labels: urgent

#292 Change golem_messages version from v2.3.1 to v2.4.0
  concent_api/core/tests/test_unit_authentication_utilities.py
  concent_api/requirements.lock
  concent_api/requirements.txt
  concent_api/utils/helpers.py
  concent_api/utils/shortcuts.py
Labels: urgent

#293 Fix for Concent sends BAD REQUEST when RejectReportComputedTask.canno…
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_auth_report_computed_task.py
  concent_api/core/validation.py
Labels: urgent

#321 Add SubtaskTimeLimitExceeded handling in receive/
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_report_computed_task.py
Labels: report use case, urgent
