Repository golemfactory/concent, pull requests merged in 2018-05, with the labels that each got.

#334 Set default database empty
  README.md
  concent_api/concent_api/constants.py
  concent_api/concent_api/settings/base.py
  concent_api/concent_api/settings/development.py
  concent_api/concent_api/settings/testing.py
  concent_api/concent_api/system_check.py
  concent_api/concent_api/tests/test_check_atomic_requests.py
  concent_api/core/tests/utils.py
  concent_api/core/views.py
  concent_api/utils/decorators.py
  concent_api/utils/tests/test_api_view.py
  concent_api/utils/tests/test_decorators.py
Labels: sync with deployment

#374 Fix validation of RejectReportComputedTask
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_report_computed_task.py
Labels: urgent

#376 sign AckReportComputedTask() generated by Concent with priv_key
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_report_computed_task.py
  concent_api/core/tests/utils.py
Labels: urgent

#381 Change Reason in ServiceRefused in Acceptance Use Case
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_accept_or_reject_results.py
Labels: acceptance use case, bug

#389 Add force payment to acceptance use case
  concent_api/api-integration-force-accept-or-reject-results-test.py
  concent_api/core/message_handlers.py
Labels: acceptance use case, bug, urgent

#414 remove '_' from api-integration-tests 'task_id'
  concent_api/api-integration-force-get-task-result-test.py
  concent_api/api_testing_common.py
Labels: bug, urgent
