Repository golemfactory/concent, pull requests merged in 2018-07, with the labels that each got.

#603 Add type annotations to verifier utils
  concent_api/verifier/utils.py
Labels: chore

#614 [M]Allow longer length of paths fields in VerificationRequest
  concent_api/conductor/constants.py
  concent_api/conductor/migrations/0007_auto_20180709_1526.py
  concent_api/conductor/models.py
Labels: bug

#624 Change signature for RCT nested in ARCT
  concent_api/api-integration-force-report-computed-task-test.py
  concent_api/concent_api/tests/test_shutdown_mode.py
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_auth_report_computed_task.py
  concent_api/core/tests/test_integration_report_computed_task.py
Labels: bug, report use case, urgent

#642 golem-messages update to v2.10.1
  concent_api/requirements.lock
  concent_api/requirements.txt
Labels: golem messages
