Repository golemfactory/concent, pull requests merged in 2018-06, with the labels that each got.

#435 Chore passing sizes and checksums from control cluster to verifier
  concent_api/conductor/tasks.py
  concent_api/conductor/tests/test_integration_conductor.py
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_subtask_results_verify.py
  concent_api/core/tests/test_unit_transfer_operation.py
  concent_api/core/tests/utils.py
  concent_api/core/transfer_operations.py
  concent_api/verifier/tasks.py
  concent_api/verifier/tests/test_integration_verification.py
Labels: chore, verification use case

#364 Chore return json on http 5xx errors (second time ;))
  concent_api/concent_api/constants.py
  concent_api/concent_api/middleware.py
  concent_api/concent_api/settings/base.py
  concent_api/concent_api/settings/development.py
  concent_api/concent_api/settings/testing.py
  concent_api/concent_api/tests/test_middleware.py
  concent_api/requirements.lock
  concent_api/requirements.txt
  concent_api/utils/constants.py
Labels: urgent

#443 update pylint versions
  requirements-development.txt
Labels: chore

#456 Change client_public_key from requestor to provider in SubtaskResultsVerify message
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_subtask_results_verify.py
  concent_api/core/validation.py
Labels: bug

#466 Add custom exception message from golem_messages to our Http400 response
  concent_api/core/validation.py
Labels: bug

#467 remove compute_task_def['deadline'] overwrite in concent validation
  concent_api/core/message_handlers.py
  concent_api/core/validation.py
Labels: bug, urgent

#491 Fix ForceReportComputedTask sending: proper reasons have been added
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_report_computed_task.py
Labels: bug, urgent

#490 Add compute_task_def['deadline'] conversion to int() in FTT creation
  concent_api/core/tests/test_unit_transfer_operation.py
  concent_api/core/transfer_operations.py
Labels: bug, urgent

#495 Bugfix transfer verification result function from verifier to core
  concent_api/concent_api/celery.py
  concent_api/core/constants.py
  concent_api/core/tasks.py
  concent_api/core/tests/test_verification_result_task.py
  concent_api/verifier/constants.py
  concent_api/verifier/tasks.py
  concent_api/verifier/tests/test_integration_verification.py
Labels: bug, verification use case

#498 Bugfix transistion to additional verification state doesent add svt time to next deadline
  concent_api/core/subtask_helpers.py
  concent_api/core/tasks.py
Labels: bug, verification use case

#504 Switch ReportComputedTask massage creation to golem factories
  concent_api/api-integration-force-report-computed-task-test.py
Labels: bug

#573 Chore refactor verification
  concent_api/api-integration-additional-verification-test.py
  concent_api/api_testing_common.py
  concent_api/common/helpers.py
  concent_api/conductor/migrations/0002_auto_20180627_1335.py
  concent_api/conductor/models.py
  concent_api/core/tests/utils.py
  concent_api/core/transfer_operations.py
  concent_api/verifier/decorators.py
  concent_api/verifier/exceptions.py
  concent_api/verifier/tasks.py
  concent_api/verifier/tests/test_integration_verification.py
  concent_api/verifier/utils.py
Labels: chore, urgent, verification use case

#577 Bugfix Change cluster storage addres to internal
  concent_api/verifier/utils.py
Labels: bug, not in pivotal, verification use case
