Repository golemfactory/concent, pull requests merged in 2018-12, with the labels that each got.

#1004 Fix SubtaskResultsAccepted signature not checked force payment case
  concent_api/concent_api/tests/test_shutdown_mode.py
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_force_payment.py
Labels: urgent

#1014 Fix message type returned by Concent when there is not enough request…
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_force_payment.py
Labels: _high_priority

#1012 Add logs to handle_send_force_payment function
  concent_api/common/logging.py
  concent_api/core/message_handlers.py
Labels: _high_priority, bug, payment use case

#1020 Fix wrong payment_ts concent gives in ForcePaymentCommitted message
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_integration_force_payment.py
Labels: bug

#1030 [M]Switch "big" IntegerField() to DecimalField in core models
  concent_api/core/constants.py
  concent_api/core/migrations/0019_auto_20181217_1255.py
  concent_api/core/models.py
  concent_api/core/tests/test_unit_model.py
Labels: bug, sentry

#1008 Add test for multiple providers ethereum addresses in ForcePayment
  concent_api/core/tests/test_integration_force_payment.py
Labels: _high_priority

#1028 Add validation for force_payment message
  concent_api/core/message_handlers.py
  concent_api/core/tests/test_unit_message_handlers.py
  concent_api/core/tests/test_unit_validation.py
Labels: bug, sentry
